name: Auto Bookkeeping

on:
  schedule:
    # 毎週月曜日の午前9時（JST）に実行
    - cron: '0 0 * * 1'  # UTC 00:00 = JST 09:00
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (確認のみ、登録しない)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      limit:
        description: '処理する取引数の上限 (テスト用)'
        required: false
        default: '100'
        type: string

jobs:
  process-transactions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run bookkeeping process
      env:
        FREEE_ACCESS_TOKEN: ${{ secrets.FREEE_ACCESS_TOKEN }}
        FREEE_REFRESH_TOKEN: ${{ secrets.FREEE_REFRESH_TOKEN }}
        FREEE_CLIENT_ID: ${{ secrets.FREEE_CLIENT_ID }}
        FREEE_CLIENT_SECRET: ${{ secrets.FREEE_CLIENT_SECRET }}
        FREEE_COMPANY_ID: ${{ secrets.FREEE_COMPANY_ID }}
        FREEE_CLAUDE_API_KEY: ${{ secrets.FREEE_CLAUDE_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}
        TRANSACTION_LIMIT: ${{ github.event.inputs.limit || '100' }}
        ALWAYS_NOTIFY: ${{ secrets.ALWAYS_NOTIFY || 'false' }}
        USE_ENHANCED_MODE: ${{ secrets.USE_ENHANCED_MODE || 'false' }}
      run: |
        pip install pynacl  # トークン暗号化用
        if [ "$USE_ENHANCED_MODE" = "true" ]; then
          echo "過去の取引履歴を活用する拡張モードで実行します"
          python src/enhanced_main.py
        else
          echo "標準モードで実行します"
          python src/main.py
        fi
    
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bookkeeping-results-${{ github.run_id }}
        path: |
          results_*.json
        retention-days: 30
